#Minecraft server properties
#Tue Aug 18 14:36:08 UTC 2026
accepts-transfers=false
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
cd=AbsolSrv
chat-spam-threshold-seconds=10
command-spam-threshold-seconds=10
cp=-r * ../repo-limpio/  \# Copia todo (incluyendo archivos ocultos)
debug=false
difficulty=hard
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
git=commit -m "Primer commit limpio - estado actual del servidor"
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=N1ZRLR8nrBoR86aHvsHlD4nUrrZjK2VpJZrTGce8
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
mkdir=../repo-limpio
motd=A Minecraft Server
mv=repo-limpio AbsolSrv
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=1000000
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://download.mc-packs.net/pack/f5f30ae73771e6d9392ce80cec21a3fc53423583.zip
resource-pack-id=be1caf4a-5b37-450a-9a2f-13ec5b819aba
resource-pack-prompt={"text"\:"Our server uses a custom resource pack\!", "color"\:"gold"}
resource-pack-sha1=f5f30ae73771e6d9392ce80cec21a3fc53423583
rm=-rf AbsolSrv  
server-ip=
server-port=25565
simulation-distance=10
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=10
white-list=false
